<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="1.5.378.176" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <ProjectReference Include="../IIoT.FaultDiagnosis.Domain/IIoT.FaultDiagnosis.Domain.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.81" />
  </ItemGroup>
</Project>
