// <auto-generated />
using System;
using IIoT.FaultDiagnosis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IIoT.FaultDiagnosis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FaultDiagnosisDbContext))]
    [Migration("20260912133448_Phase2AllowStandaloneCommunicationRecords")]
    partial class Phase2AllowStandaloneCommunicationRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.CommunicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_id");

                    b.Property<Guid?>("ExperimentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_run_id");

                    b.Property<string>("FaultType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fault_type");

                    b.Property<string>("ParsedValue")
                        .HasColumnType("text")
                        .HasColumnName("parsed_value");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("protocol_type");

                    b.Property<string>("RawRequest")
                        .HasColumnType("text")
                        .HasColumnName("raw_request");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<double?>("ResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("response_time_ms");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("DeviceId", "StartedAt")
                        .HasDatabaseName("ix_communication_records_device_started_at");

                    b.HasIndex("ExperimentRunId", "CreatedAt")
                        .HasDatabaseName("ix_communication_records_run_created_at");

                    b.ToTable("communication_records", (string)null);
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("protocol_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled", "ProtocolType")
                        .HasDatabaseName("ix_devices_enabled_protocol");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.DiagnosisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommunicationRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_record_id");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DiagnosisDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("diagnosis_duration_ms");

                    b.Property<string>("DiagnosisMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("diagnosis_method");

                    b.Property<string>("PossibleCauses")
                        .HasColumnType("jsonb")
                        .HasColumnName("possible_causes");

                    b.Property<string>("PredictedFaultType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("predicted_fault_type");

                    b.Property<string>("SuggestedActions")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_actions");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationRecordId")
                        .HasDatabaseName("ix_diagnosis_results_record_id");

                    b.ToTable("diagnosis_results", (string)null);
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualFaultType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actual_fault_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("device_count");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PollingIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("polling_interval_ms");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("protocol_type");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TagCount")
                        .HasColumnType("integer")
                        .HasColumnName("tag_count");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_experiments_created_at");

                    b.ToTable("experiments", (string)null);
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.ExperimentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AverageResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("average_response_time_ms");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("CpuAverage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cpu_average");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_id");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failure_count");

                    b.Property<double?>("MaxResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("max_response_time_ms");

                    b.Property<decimal?>("MemoryAverageMb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("memory_average_mb");

                    b.Property<double?>("MinResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("min_response_time_ms");

                    b.Property<int>("RunNumber")
                        .HasColumnType("integer")
                        .HasColumnName("run_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("success_count");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId", "RunNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_experiment_runs_experiment_run_number");

                    b.ToTable("experiment_runs", (string)null);
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.SystemMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CpuPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cpu_percent");

                    b.Property<Guid>("ExperimentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_run_id");

                    b.Property<decimal?>("GcHeapMb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("gc_heap_mb");

                    b.Property<int?>("HandleCount")
                        .HasColumnType("integer")
                        .HasColumnName("handle_count");

                    b.Property<decimal>("MemoryMb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("memory_mb");

                    b.Property<int?>("ThreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("thread_count");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentRunId", "Timestamp")
                        .HasDatabaseName("ix_system_metrics_run_timestamp");

                    b.ToTable("system_metrics", (string)null);
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.CommunicationRecord", b =>
                {
                    b.HasOne("IIoT.FaultDiagnosis.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IIoT.FaultDiagnosis.Domain.Entities.Experiment", "Experiment")
                        .WithMany("CommunicationRecords")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IIoT.FaultDiagnosis.Domain.Entities.ExperimentRun", "ExperimentRun")
                        .WithMany("CommunicationRecords")
                        .HasForeignKey("ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");

                    b.Navigation("Experiment");

                    b.Navigation("ExperimentRun");
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.DiagnosisResult", b =>
                {
                    b.HasOne("IIoT.FaultDiagnosis.Domain.Entities.CommunicationRecord", "CommunicationRecord")
                        .WithMany("DiagnosisResults")
                        .HasForeignKey("CommunicationRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunicationRecord");
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.ExperimentRun", b =>
                {
                    b.HasOne("IIoT.FaultDiagnosis.Domain.Entities.Experiment", "Experiment")
                        .WithMany("Runs")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.SystemMetric", b =>
                {
                    b.HasOne("IIoT.FaultDiagnosis.Domain.Entities.ExperimentRun", "ExperimentRun")
                        .WithMany("SystemMetrics")
                        .HasForeignKey("ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperimentRun");
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.CommunicationRecord", b =>
                {
                    b.Navigation("DiagnosisResults");
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.Experiment", b =>
                {
                    b.Navigation("CommunicationRecords");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("IIoT.FaultDiagnosis.Domain.Entities.ExperimentRun", b =>
                {
                    b.Navigation("CommunicationRecords");

                    b.Navigation("SystemMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
